CREATE TABLE IF NOT EXISTS gift_employees (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  corp_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  wecom_user_id VARCHAR(128) COLLATE utf8mb4_bin NOT NULL,
  display_name VARCHAR(128) NOT NULL,
  department_ids JSON NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'employee',
  employment_status VARCHAR(32) NOT NULL DEFAULT 'active',
  last_login_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_employee_wecom_identity (corp_id, wecom_user_id),
  KEY idx_gift_employee_status (employment_status),
  CONSTRAINT chk_gift_employee_role CHECK (role IN ('employee', 'operator', 'admin')),
  CONSTRAINT chk_gift_employee_status CHECK (employment_status IN ('active', 'inactive'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS gift_assets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  owner_employee_id BIGINT UNSIGNED NULL,
  asset_kind VARCHAR(32) NOT NULL,
  storage_provider VARCHAR(16) NOT NULL DEFAULT 'oss',
  storage_region VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  bucket_name VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  object_key VARCHAR(1024) NOT NULL,
  object_key_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  original_filename VARCHAR(255) NULL,
  content_type VARCHAR(128) CHARACTER SET ascii COLLATE ascii_general_ci NULL,
  file_extension VARCHAR(16) CHARACTER SET ascii COLLATE ascii_general_ci NULL,
  size_bytes BIGINT UNSIGNED NULL,
  sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  visibility VARCHAR(16) NOT NULL DEFAULT 'private',
  asset_status VARCHAR(16) NOT NULL DEFAULT 'active',
  metadata JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_asset_storage_locator (bucket_name, object_key_hash),
  KEY idx_gift_asset_owner_created (owner_employee_id, created_at),
  KEY idx_gift_asset_kind_status (asset_kind, asset_status),
  CONSTRAINT fk_gift_asset_owner FOREIGN KEY (owner_employee_id) REFERENCES gift_employees (id) ON DELETE SET NULL,
  CONSTRAINT chk_gift_asset_kind CHECK (asset_kind IN ('reference_image', 'render_image', 'edit_mask', 'model_file', 'model_preview', 'business_attachment')),
  CONSTRAINT chk_gift_asset_visibility CHECK (visibility IN ('private', 'internal')),
  CONSTRAINT chk_gift_asset_status CHECK (asset_status IN ('active', 'deleted'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS gift_models (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  source_type VARCHAR(24) NOT NULL,
  owner_employee_id BIGINT UNSIGNED NULL,
  title_zh VARCHAR(255) NOT NULL,
  title_en VARCHAR(255) NULL,
  description_zh TEXT NULL,
  description_en TEXT NULL,
  category VARCHAR(64) NOT NULL,
  use_case VARCHAR(255) NULL,
  tags JSON NOT NULL,
  supported_finishes JSON NOT NULL,
  model_asset_id BIGINT UNSIGNED NULL,
  preview_asset_id BIGINT UNSIGNED NULL,
  model_format VARCHAR(16) CHARACTER SET ascii COLLATE ascii_general_ci NULL,
  dimension_x_mm DECIMAL(12,3) NULL,
  dimension_y_mm DECIMAL(12,3) NULL,
  dimension_z_mm DECIMAL(12,3) NULL,
  volume_cm3 DECIMAL(16,4) NULL,
  surface_area_mm2 DECIMAL(18,3) NULL,
  triangle_count BIGINT UNSIGNED NULL,
  printable_status VARCHAR(24) NOT NULL DEFAULT 'unchecked',
  publication_status VARCHAR(24) NOT NULL DEFAULT 'draft',
  version_number INT UNSIGNED NOT NULL DEFAULT 1,
  created_by_employee_id BIGINT UNSIGNED NULL,
  approved_by_employee_id BIGINT UNSIGNED NULL,
  approved_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_model_slug (slug),
  KEY idx_gift_model_catalog (publication_status, category, created_at),
  KEY idx_gift_model_owner (owner_employee_id, created_at),
  CONSTRAINT fk_gift_model_owner FOREIGN KEY (owner_employee_id) REFERENCES gift_employees (id) ON DELETE SET NULL,
  CONSTRAINT fk_gift_model_asset FOREIGN KEY (model_asset_id) REFERENCES gift_assets (id) ON DELETE SET NULL,
  CONSTRAINT fk_gift_model_preview FOREIGN KEY (preview_asset_id) REFERENCES gift_assets (id) ON DELETE SET NULL,
  CONSTRAINT fk_gift_model_creator FOREIGN KEY (created_by_employee_id) REFERENCES gift_employees (id) ON DELETE SET NULL,
  CONSTRAINT fk_gift_model_approver FOREIGN KEY (approved_by_employee_id) REFERENCES gift_employees (id) ON DELETE SET NULL,
  CONSTRAINT chk_gift_model_source CHECK (source_type IN ('catalog', 'ai_generated', 'employee_upload')),
  CONSTRAINT chk_gift_model_format CHECK (model_format IS NULL OR model_format IN ('stl', 'obj', '3mf', 'glb', 'gltf')),
  CONSTRAINT chk_gift_model_printable CHECK (printable_status IN ('unchecked', 'checking', 'passed', 'failed')),
  CONSTRAINT chk_gift_model_publication CHECK (publication_status IN ('draft', 'review', 'published', 'archived')),
  CONSTRAINT chk_gift_model_version CHECK (version_number > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS gift_ai_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_uid CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  employee_id BIGINT UNSIGNED NOT NULL,
  job_type VARCHAR(24) NOT NULL,
  provider VARCHAR(64) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  model_name VARCHAR(128) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  provider_job_id VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NULL,
  job_status VARCHAR(24) NOT NULL DEFAULT 'queued',
  progress_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,
  prompt_text TEXT NULL,
  input_payload JSON NULL,
  output_payload JSON NULL,
  source_asset_id BIGINT UNSIGNED NULL,
  mask_asset_id BIGINT UNSIGNED NULL,
  output_asset_id BIGINT UNSIGNED NULL,
  result_model_id BIGINT UNSIGNED NULL,
  error_code VARCHAR(128) NULL,
  error_message TEXT NULL,
  submitted_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  started_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_ai_job_uid (job_uid),
  KEY idx_gift_ai_job_employee_created (employee_id, submitted_at),
  KEY idx_gift_ai_job_provider_task (provider, provider_job_id),
  KEY idx_gift_ai_job_status_updated (job_status, updated_at),
  CONSTRAINT fk_gift_ai_job_employee FOREIGN KEY (employee_id) REFERENCES gift_employees (id) ON DELETE RESTRICT,
  CONSTRAINT fk_gift_ai_job_source_asset FOREIGN KEY (source_asset_id) REFERENCES gift_assets (id) ON DELETE SET NULL,
  CONSTRAINT fk_gift_ai_job_mask_asset FOREIGN KEY (mask_asset_id) REFERENCES gift_assets (id) ON DELETE SET NULL,
  CONSTRAINT fk_gift_ai_job_output_asset FOREIGN KEY (output_asset_id) REFERENCES gift_assets (id) ON DELETE SET NULL,
  CONSTRAINT fk_gift_ai_job_result_model FOREIGN KEY (result_model_id) REFERENCES gift_models (id) ON DELETE SET NULL,
  CONSTRAINT chk_gift_ai_job_type CHECK (job_type IN ('render', 'image_edit', 'image_to_3d', 'render_to_3d')),
  CONSTRAINT chk_gift_ai_job_status CHECK (job_status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  CONSTRAINT chk_gift_ai_job_progress CHECK (progress_percent <= 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS gift_print_requests (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  request_no VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  requester_employee_id BIGINT UNSIGNED NOT NULL,
  request_type VARCHAR(32) NOT NULL,
  model_id BIGINT UNSIGNED NULL,
  source_asset_id BIGINT UNSIGNED NULL,
  title VARCHAR(255) NOT NULL,
  customer_company VARCHAR(255) NULL,
  business_scene VARCHAR(128) NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  finish_type VARCHAR(24) NOT NULL DEFAULT 'white',
  paint_color CHAR(7) CHARACTER SET ascii COLLATE ascii_general_ci NULL,
  requested_completion_date DATE NULL,
  pickup_location VARCHAR(255) NULL,
  request_notes TEXT NULL,
  specifications JSON NULL,
  priority VARCHAR(16) NOT NULL DEFAULT 'normal',
  request_status VARCHAR(24) NOT NULL DEFAULT 'submitted',
  assigned_to_employee_id BIGINT UNSIGNED NULL,
  reviewed_by_employee_id BIGINT UNSIGNED NULL,
  reviewed_at DATETIME(3) NULL,
  submitted_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uq_gift_print_request_no (request_no),
  KEY idx_gift_request_requester_created (requester_employee_id, created_at),
  KEY idx_gift_request_status_deadline (request_status, requested_completion_date),
  KEY idx_gift_request_assignee_status (assigned_to_employee_id, request_status),
  CONSTRAINT fk_gift_request_requester FOREIGN KEY (requester_employee_id) REFERENCES gift_employees (id) ON DELETE RESTRICT,
  CONSTRAINT fk_gift_request_model FOREIGN KEY (model_id) REFERENCES gift_models (id) ON DELETE SET NULL,
  CONSTRAINT fk_gift_request_source_asset FOREIGN KEY (source_asset_id) REFERENCES gift_assets (id) ON DELETE SET NULL,
  CONSTRAINT fk_gift_request_assignee FOREIGN KEY (assigned_to_employee_id) REFERENCES gift_employees (id) ON DELETE SET NULL,
  CONSTRAINT fk_gift_request_reviewer FOREIGN KEY (reviewed_by_employee_id) REFERENCES gift_employees (id) ON DELETE SET NULL,
  CONSTRAINT chk_gift_request_type CHECK (request_type IN ('catalog_gift', 'ai_gift', 'business_sample')),
  CONSTRAINT chk_gift_request_quantity CHECK (quantity > 0),
  CONSTRAINT chk_gift_request_finish CHECK (finish_type IN ('white', 'paint', 'bronze', 'other')),
  CONSTRAINT chk_gift_request_paint_color CHECK (paint_color IS NULL OR paint_color REGEXP '^#[0-9A-Fa-f]{6}$'),
  CONSTRAINT chk_gift_request_priority CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  CONSTRAINT chk_gift_request_status CHECK (request_status IN ('draft', 'submitted', 'reviewing', 'approved', 'rejected', 'queued', 'printing', 'ready', 'completed', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS gift_request_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  request_id BIGINT UNSIGNED NOT NULL,
  actor_employee_id BIGINT UNSIGNED NULL,
  event_type VARCHAR(32) NOT NULL,
  from_status VARCHAR(24) NULL,
  to_status VARCHAR(24) NULL,
  comment_text TEXT NULL,
  event_payload JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_gift_request_event_timeline (request_id, created_at),
  KEY idx_gift_request_event_actor (actor_employee_id, created_at),
  CONSTRAINT fk_gift_request_event_request FOREIGN KEY (request_id) REFERENCES gift_print_requests (id) ON DELETE CASCADE,
  CONSTRAINT fk_gift_request_event_actor FOREIGN KEY (actor_employee_id) REFERENCES gift_employees (id) ON DELETE SET NULL,
  CONSTRAINT chk_gift_request_event_type CHECK (event_type IN ('created', 'status_changed', 'assigned', 'commented', 'updated', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
